module.exports = function(app, cMongo, cRedis, conf, log) {

    var qs = require('querystring'),
        async = require('async'),
        ObjectID = require('mongodb').ObjectID;

    // User routes:
    app.use('/user/get', wrap(getUser));

    // Helpers:
    // --------

    function wrap(handler) {

        // wrap a handler with generic operations.
        // in this order:
        // 1. validate session and obtain user id from redis
        // 2. run handler
        // 3. get the content generated by 'handler' and send the response.
        // 'handler' gets 4 arguments: req, res, userId, next.
        // next(err, content). content is a json object generated by 'handler'.

        return function(req, res) {

            async.waterfall([

                function(next) {
                    verifySessionAndGetUserId(req.cookies[conf.sessionKey.cookie], next);
                },

                function(userId, next) {
                    handler(req, res, userId, next);
                }

            ], function(err, content) {

                if (err) {
                    return res.json({
                        success: false,
                        error: err
                    });
                }

                // the API always responds with json
                content.success = true;
                res.json(content);

            });

        }

    }

    function verifySessionAndGetUserId(sessionKey, next) {

        var sessionRedisKey = conf.redis.sessionPrefix + sessionKey;

        cRedis.hgetall(sessionRedisKey, function(err, hash) {

            if (err) {
                log('Redis error. %s', err);
                return next('Redis error');
            }

            if (!hash) {
                return next('Session key does not exist on server');
            }

            var now = new Date().getTime();
            var last = parseInt(hash.last);
            var userId = hash.userid;

            if (now - last > conf.sessionKey.serverRefreshInterval) {
                return next('Session key expired');
            }

            cRedis.hset(sessionRedisKey, 'last', now, function(err) {

                if (err) {
                    log('Redis error. %s', err);
                    return next('Redis error');
                }

                next(null, userId);

            });

        });

    }

    // Handlers:
    // ---------

    function getUser(req, res, userId, next) {

        cMongo.collection(conf.mongo.usersCollection).findOne({
            _id: ObjectID(userId)
        }, function(err, doc) {

            if (err) {
                log('Unable to get user.', err);
                return next('Unable to get user');
            }

            next(null, doc);

        });

    }

}